services:
  phylogenetic-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input_data:/app/input_data
      - ./output_data:/app/output_data
    command: >
      --job phylogenetic-tree-ipa-random-choice

      --input-type sql
      --input-type-path /app/input_data/SadownikDB.sqlite
      --input-type-id sadownikdb_1

      --ipa-rules /app/input_data/ipa_rules.json
      --ipa-rules-id ipa_rules_1
      
      --custom-ipa-distance /app/input_data/ipa_letter_distance.csv
      --custom-ipa-distance-id custom-ipa-distance-1
      
      --map-idb-to-name /app/input_data/map_idb_to_name.json

      --normalization-rules /app/input_data/normalization_rules.json
      --normalization-rules-id norm-rules-1


      --output-folder-path /app/output_data/

      --book-idbs 29,28,44,43,39,38,37,46,36,33,42
      --chapters 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28

      --random-ipa-iterations 1000
      --parallel-workers 3
      --cache-path /app/input_data/cache.sqlite
      --verbose normal


# launching 4 first sentences from litte prince
# --input-type json
# --input-type-path /app/input_data/four_phrases.json
# --input-type-id four_phrases-1

